# Banque : ANN

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3: 13].values
y = dataset.iloc[:, 13].values

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
ct = ColumnTransformer([("categorical_features", OneHotEncoder(),[1])], remainder="passthrough")
X = ct.fit_transform(X)
X = X[:,1:]

In [4]:

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Importation des modules de keras

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout


Using TensorFlow backend.


### Initialisation

In [6]:
classifier = Sequential()

# Ajouter la couche d'entrée et une couche cachée

In [7]:
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform', input_dim=11))


In [8]:
classifier.add(Dropout(rate=0.1))

# Ajouter une deuxième couche cachée

In [9]:
classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform'))

In [10]:
classifier.add(Dropout(rate=0.1))

# Ajouter une couche de sortie

In [11]:
classifier.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [12]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

## Entrainer le réseau de neuronne

In [13]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4935 - accuracy: 0.7951
Epoch 2/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4350 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4358 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4311 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4292 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4297 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4277 - accuracy: 0.8051
Epoch 8/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4287 - accuracy: 0.8248
Epoch 9/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4299 - accuracy: 0.8226
Epoch 10/100
8000/8000 [==============================] - 1s 9

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-297258a82b16>", line 1, in <module>
    classifier.fit(X_train, y_train, batch_size=10, epochs=100)
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\keras\engine\training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\tensorflow_core\python\eager\function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "C:\Users\USER\anacond

## Prediction

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1546,   49],
       [ 273,  132]], dtype=int64)

Faire une prédiction : <br>
Pays : France <br>
Score de crédit : 600 <br>
Genre : Masculin <br>
Âge : 40 ans <br>
Durée depuis entrée dans la banque : 3 ans <br>
Balance : 60000 € <br>
Nombre de produits : 2 <br>
Carte de crédit ? Oui <br>
Membre actif ? : Oui <br>
Salaire estimé : 50000 € <br>

In [ ]:

new_prediction = classifier.predict(sc.transform(np.array([[0, 0, 600, 0, 40, 3, 60000, 2, 1 , 1 , 50000]])))

In [ ]:
new_prediction = (new_prediction > 0.5)
new_prediction

array([[False]])

In [ ]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[1546,   49],
       [ 273,  132]], dtype=int64)

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units=12, activation='relu', kernel_initializer='uniform', input_dim=11))
    classifier.add(Dropout(rate=0.1))
    classifier.add(Dense(units=12, activation='relu', kernel_initializer='uniform'))
    classifier.add(Dropout(rate=0.1))
    classifier.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))
    classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return classifier

In [ ]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, epochs=100)


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-314bb13693f8>", line 1, in <module>
    classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, epochs=100)
NameError: name 'KerasClassifier' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\envdl\lib\site-packages\IPython\core\ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb,

In [ ]:
precisions = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10, n_jobs=-1)

In [ ]:
precisions.mean()

0.842125004529953

ERROR! Session/line number was not unique in database. History logging moved to new session 344


In [ ]:
precisions.std()

0.019056244935491733

In [ ]:
# from keras.wrappers.scikit_learn import KerasClassifier
# from sklearn.model_selection import GridSearchCV

# def build_classifier(optimizer):
#     classifier = Sequential()
#     classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform', input_dim=11))
#     # classifier.add(Dropout(rate=0.1))
#     classifier.add(Dense(units=6, activation='relu', kernel_initializer='uniform'))
#     # classifier.add(Dropout(rate=0.1))
#     classifier.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))
#     classifier.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy"])
#     return classifier

# classifier = KerasClassifier(build_fn=build_classifier)

# parameters = {
#     "batch_size":[25,32], 
#     "epochs": [100,500],
#     "optimizer": ['rmsprop','adam']
# }

# grid_search = GridSearchCV(estimator=classifier,param_grid=parameters, scoring='accuracy',cv=10)

# grid_search = grid_search.fit(X_train, y_train)

# print(grid_search.best_params_)
# print(grid_search.best_score_)

Epoch 1/100
7200/7200 [==============================] - 0s 47us/step - loss: 0.6040 - accuracy: 0.7953
Epoch 2/100
7200/7200 [==============================] - 0s 34us/step - loss: 0.4545 - accuracy: 0.7971
Epoch 3/100
7200/7200 [==============================] - 0s 33us/step - loss: 0.4365 - accuracy: 0.7971
Epoch 4/100
7200/7200 [==============================] - 0s 43us/step - loss: 0.4305 - accuracy: 0.7971 0s - loss: 0.4312 - accuracy
Epoch 5/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4272 - accuracy: 0.7971
Epoch 6/100
7200/7200 [==============================] - 0s 32us/step - loss: 0.4240 - accuracy: 0.7971
Epoch 7/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4209 - accuracy: 0.8004
Epoch 8/100
7200/7200 [==============================] - 0s 38us/step - loss: 0.4178 - accuracy: 0.8222
Epoch 9/100
7200/7200 [==============================] - 0s 39us/step - loss: 0.4151 - accuracy: 0.8265
Epoch 10/100
7200/7200 [===========