 # FORMATION - COURS SUR NUMPY 
<img src="../img/Logo/numpy.png" alt="drawing" width="100"/>

---

[Installation de numpy](#installation-numpy)

In [2]:
import numpy as np

## 1° - Méthode pour créer des tableau et les manipulés

> Création d'un tableau 1 dimension, la fonction `shape` sert à connaitre le nombre de ligne et colonne

In [3]:
A = np.array([1,2,3])
A.shape

(3,)

> Créaton d'un tableau 2 dimension contenant que des 0 (Attention au tuple)

In [4]:
B = np.zeros((2,3))
print(B)
print(B.shape)
type(B.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


tuple

> Création d'un tableau contenant que des 1 

In [5]:
C = np.ones((3,4))
print(C)
C.size

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12

> Rarement utilisé

In [6]:
D = np.full((2,9),9)
D

array([[9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])

> Généré un tableau aléatoirement (pour fixer la fonction aléatoire on utilise seed)

In [7]:
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

> Création d'une matrice d'identité

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

> Création d'un tableau à 1 dimension np.linspace(<b class="alert-warning">début</b>, fin, quantité, dtype) <br>
> dtype c'est la place numérique qu'on peux lui donnée

In [9]:
np.linspace(0,10,20, dtype = np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

> Création d'un tableau à 1 dimension np.arange(début, fin, pas)

In [10]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [11]:
A = np.zeros((3,2))
B = np.ones((3,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


> Colle les tableaux à coté de l'un et de l'autre

In [13]:
C = np.hstack((A,B))

print(C)
C.shape

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


(3, 4)

>  Colle les tableaux superposé l'un à l'autre

In [14]:
D = np.vstack((A,B))

print(D)
D.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


(6, 2)

> la fonction concatenate fait la meme chose que vstack() ou hstack() en fonction de l'abcisse <br>
> Méthode concatenate = hstack()

In [15]:
np.concatenate((A,B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

> Méthode concatenate = vstack()

In [16]:
D = np.concatenate((A,B), axis=0)
print(D)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


> Redimensionner un tableau grace à reshape

In [17]:
D.reshape((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

> Pour ajouter le 1 dans shape

In [18]:
A = np.array([1,2,3])
A.shape

(3,)

In [19]:
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

> Pour supprimer le 1 dans shape

In [20]:
A = A.squeeze()
A.shape

(3,)

> Pour aplatir un tableau à plusieurs dimensions en une dimensions avec Ravel()

In [21]:
D = D.reshape((3,4))
D.ravel().shape

(12,)

> Pour casser un tableau à 1 dimensions

In [26]:
array = np.array([15,16,17,12,49,52,12,14,36])
array1, array2, array3, array4 = np.split(array,[2,4,6])

In [27]:
print(array1, array2, array3, array4)

[15 16] [17 12] [49 52] [12 14 36]


> Pour donner le compter le nombre de valeur présente dans le tableau

In [28]:
len(array1)

2

> Pour casser un tableau à plusieurs dimensions avec np.vsplit() de façon vertical

In [31]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [34]:
array1, array1bis = np.vsplit(array, [2])
print('Premier tableau array1 : ')
print(array1)
print('Premier tableau array1bis : ')
print(array1bis)

Premier tableau array1 : 
[[1 2 3]
 [4 5 6]]
Premier tableau array1bis : 
[[7 8 9]]


> Pour casser un tableau à plusieurs dimensions avec np.vsplit() de façon horizontal

In [35]:
array1, array1bis = np.hsplit(array, [2])
print('Premier tableau array1 : ')
print(array1)
print('Premier tableau array1bis : ')
print(array1bis)

Premier tableau array1 : 
[[1 2]
 [4 5]
 [7 8]]
Premier tableau array1bis : 
[[3]
 [6]
 [9]]


> Calcul avec les tableaux

In [37]:
array = np.random.randint(350, size=(10,9))
array

array([[222, 123,  82, 227, 148, 209,  50, 270,  41],
       [ 58, 193,  36, 266,  86,  43,  11, 258, 307],
       [ 80,  32, 182, 128, 294, 275, 174,  42, 184],
       [ 77, 286, 280, 125, 258,   3,  94, 226, 269],
       [296, 328,  19,  95, 328, 248, 180, 323, 317],
       [270, 260, 237, 139,  86, 109, 331, 184,  16],
       [152, 149, 110,  25, 117,  83, 161, 228, 251],
       [121, 326, 287,  13, 327, 184, 152,  79,  41],
       [274,  40, 207, 267, 166, 111, 349, 129, 223],
       [300, 216,  24,  67, 259, 234, 204, 291, 214]])

> Additioner un tableau un nombre avec le tableau ci-dessus

In [38]:
array + 2

array([[224, 125,  84, 229, 150, 211,  52, 272,  43],
       [ 60, 195,  38, 268,  88,  45,  13, 260, 309],
       [ 82,  34, 184, 130, 296, 277, 176,  44, 186],
       [ 79, 288, 282, 127, 260,   5,  96, 228, 271],
       [298, 330,  21,  97, 330, 250, 182, 325, 319],
       [272, 262, 239, 141,  88, 111, 333, 186,  18],
       [154, 151, 112,  27, 119,  85, 163, 230, 253],
       [123, 328, 289,  15, 329, 186, 154,  81,  43],
       [276,  42, 209, 269, 168, 113, 351, 131, 225],
       [302, 218,  26,  69, 261, 236, 206, 293, 216]])

OU

In [43]:
np.add(array, 2)

array([[224, 125,  84, 229, 150, 211,  52, 272,  43],
       [ 60, 195,  38, 268,  88,  45,  13, 260, 309],
       [ 82,  34, 184, 130, 296, 277, 176,  44, 186],
       [ 79, 288, 282, 127, 260,   5,  96, 228, 271],
       [298, 330,  21,  97, 330, 250, 182, 325, 319],
       [272, 262, 239, 141,  88, 111, 333, 186,  18],
       [154, 151, 112,  27, 119,  85, 163, 230, 253],
       [123, 328, 289,  15, 329, 186, 154,  81,  43],
       [276,  42, 209, 269, 168, 113, 351, 131, 225],
       [302, 218,  26,  69, 261, 236, 206, 293, 216]])

> Multiplier un tableau un nombre avec le tableau ci-dessus

In [39]:
array * 10

array([[2220, 1230,  820, 2270, 1480, 2090,  500, 2700,  410],
       [ 580, 1930,  360, 2660,  860,  430,  110, 2580, 3070],
       [ 800,  320, 1820, 1280, 2940, 2750, 1740,  420, 1840],
       [ 770, 2860, 2800, 1250, 2580,   30,  940, 2260, 2690],
       [2960, 3280,  190,  950, 3280, 2480, 1800, 3230, 3170],
       [2700, 2600, 2370, 1390,  860, 1090, 3310, 1840,  160],
       [1520, 1490, 1100,  250, 1170,  830, 1610, 2280, 2510],
       [1210, 3260, 2870,  130, 3270, 1840, 1520,  790,  410],
       [2740,  400, 2070, 2670, 1660, 1110, 3490, 1290, 2230],
       [3000, 2160,  240,  670, 2590, 2340, 2040, 2910, 2140]])

OU

In [45]:
np.multiply(array, 10)

array([[2220, 1230,  820, 2270, 1480, 2090,  500, 2700,  410],
       [ 580, 1930,  360, 2660,  860,  430,  110, 2580, 3070],
       [ 800,  320, 1820, 1280, 2940, 2750, 1740,  420, 1840],
       [ 770, 2860, 2800, 1250, 2580,   30,  940, 2260, 2690],
       [2960, 3280,  190,  950, 3280, 2480, 1800, 3230, 3170],
       [2700, 2600, 2370, 1390,  860, 1090, 3310, 1840,  160],
       [1520, 1490, 1100,  250, 1170,  830, 1610, 2280, 2510],
       [1210, 3260, 2870,  130, 3270, 1840, 1520,  790,  410],
       [2740,  400, 2070, 2670, 1660, 1110, 3490, 1290, 2230],
       [3000, 2160,  240,  670, 2590, 2340, 2040, 2910, 2140]])

In [41]:
array[:,0] * 10


array([2220,  580,  800,  770, 2960, 2700, 1520, 1210, 2740, 3000])

> Diviser un tableau un nombre avec le tableau ci-dessus

In [42]:
array / 2

array([[111. ,  61.5,  41. , 113.5,  74. , 104.5,  25. , 135. ,  20.5],
       [ 29. ,  96.5,  18. , 133. ,  43. ,  21.5,   5.5, 129. , 153.5],
       [ 40. ,  16. ,  91. ,  64. , 147. , 137.5,  87. ,  21. ,  92. ],
       [ 38.5, 143. , 140. ,  62.5, 129. ,   1.5,  47. , 113. , 134.5],
       [148. , 164. ,   9.5,  47.5, 164. , 124. ,  90. , 161.5, 158.5],
       [135. , 130. , 118.5,  69.5,  43. ,  54.5, 165.5,  92. ,   8. ],
       [ 76. ,  74.5,  55. ,  12.5,  58.5,  41.5,  80.5, 114. , 125.5],
       [ 60.5, 163. , 143.5,   6.5, 163.5,  92. ,  76. ,  39.5,  20.5],
       [137. ,  20. , 103.5, 133.5,  83. ,  55.5, 174.5,  64.5, 111.5],
       [150. , 108. ,  12. ,  33.5, 129.5, 117. , 102. , 145.5, 107. ]])

OU

In [46]:
np.divide(array,2)

array([[111. ,  61.5,  41. , 113.5,  74. , 104.5,  25. , 135. ,  20.5],
       [ 29. ,  96.5,  18. , 133. ,  43. ,  21.5,   5.5, 129. , 153.5],
       [ 40. ,  16. ,  91. ,  64. , 147. , 137.5,  87. ,  21. ,  92. ],
       [ 38.5, 143. , 140. ,  62.5, 129. ,   1.5,  47. , 113. , 134.5],
       [148. , 164. ,   9.5,  47.5, 164. , 124. ,  90. , 161.5, 158.5],
       [135. , 130. , 118.5,  69.5,  43. ,  54.5, 165.5,  92. ,   8. ],
       [ 76. ,  74.5,  55. ,  12.5,  58.5,  41.5,  80.5, 114. , 125.5],
       [ 60.5, 163. , 143.5,   6.5, 163.5,  92. ,  76. ,  39.5,  20.5],
       [137. ,  20. , 103.5, 133.5,  83. ,  55.5, 174.5,  64.5, 111.5],
       [150. , 108. ,  12. ,  33.5, 129.5, 117. , 102. , 145.5, 107. ]])

> Soustraction un tableau un nombre avec le tableau ci-dessus

In [44]:
np.subtract(array, 10)

array([[212, 113,  72, 217, 138, 199,  40, 260,  31],
       [ 48, 183,  26, 256,  76,  33,   1, 248, 297],
       [ 70,  22, 172, 118, 284, 265, 164,  32, 174],
       [ 67, 276, 270, 115, 248,  -7,  84, 216, 259],
       [286, 318,   9,  85, 318, 238, 170, 313, 307],
       [260, 250, 227, 129,  76,  99, 321, 174,   6],
       [142, 139, 100,  15, 107,  73, 151, 218, 241],
       [111, 316, 277,   3, 317, 174, 142,  69,  31],
       [264,  30, 197, 257, 156, 101, 339, 119, 213],
       [290, 206,  14,  57, 249, 224, 194, 281, 204]])

> Calculer la moyenne du tableau

In [47]:
np.mean(array)

175.4

OU

In [48]:
array.mean()

175.4

> Le min et max du tableau

In [55]:
array.min()

3

In [54]:
array.max()

349

> Moyenne par colonne

In [56]:
np.mean(array, axis=0)

array([185. , 195.3, 146.4, 135.2, 206.9, 149.9, 170.6, 203. , 186.3])

> Moyenne par ligne

In [57]:
np.mean(array, axis=1)

array([152.44444444, 139.77777778, 154.55555556, 179.77777778,
       237.11111111, 181.33333333, 141.77777778, 170.        ,
       196.22222222, 201.        ])

# Exercice

> Importer un fichier cvs avec numpy

La 1ère colonne est le prix des maison <br>
La 2ème colonne est la surface de la maison<br>
La 3ème colonne est la surface du terrain <br>

In [64]:
houses = np.genfromtxt('Houses.csv', delimiter=',' , dtype=int)
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

#1. Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 Euros

In [65]:
houses[:,0] = houses[:,0] * 0.86
print(houses)

[[182320   4148  25264]
 [197800   2501  11891]
 [291540   4374  25351]
 [248540   2398  22215]
 [137600   2536   9234]
 [ 73100   2368  13329]
 [ 73100   1264   8407]
 [124700   1572  12588]
 [141040   2375  16204]
 [106210   1161   9626]
 [154800   1542   8755]
 [137170   1464  14636]
 [134160   2240  21780]
 [125990   1269  11250]
 [ 87290    924   7361]
 [ 94428    768  10497]
 [156520   1320  15768]
 [ 94600   1845  12153]
 [107500   1274  13634]
 [ 68800   1905  10890]]


#2. Convertir les pieds carrés en m² sachant que 1 pied carré = 0.09m²

In [66]:
houses[:,1:] = houses[:,1:] * 0.09
print(houses)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


#3. Combien de maison ont un terrain de plus de 1000m²

In [69]:
len(houses[houses[:,2]>1000])

13

#4 . Calculer la somme totale obtenue apèrs la vente de toutes les maisons

In [70]:
np.sum(houses[:,0])

2737208

#5. Quelle est la taille de la maison vendue la plus chère ?

In [75]:
prix_max = houses[:,0].max()
print(prix_max)

291540


In [76]:
houses[houses[:,0]==prix_max]

array([[291540,    393,   2281]])

#6. Casser le array en 3 tableaux et le concatener

In [77]:
prix, taille_maison, taille_terrain = np.hsplit(houses, 3)

In [78]:
print(prix)
print(taille_maison)
print(taille_terrain)

[[182320]
 [197800]
 [291540]
 [248540]
 [137600]
 [ 73100]
 [ 73100]
 [124700]
 [141040]
 [106210]
 [154800]
 [137170]
 [134160]
 [125990]
 [ 87290]
 [ 94428]
 [156520]
 [ 94600]
 [107500]
 [ 68800]]
[[373]
 [225]
 [393]
 [215]
 [228]
 [213]
 [113]
 [141]
 [213]
 [104]
 [138]
 [131]
 [201]
 [114]
 [ 83]
 [ 69]
 [118]
 [166]
 [114]
 [171]]
[[2273]
 [1070]
 [2281]
 [1999]
 [ 831]
 [1199]
 [ 756]
 [1132]
 [1458]
 [ 866]
 [ 787]
 [1317]
 [1960]
 [1012]
 [ 662]
 [ 944]
 [1419]
 [1093]
 [1227]
 [ 980]]


In [80]:
houses_original = np.concatenate([prix, taille_maison, taille_terrain], axis = 1)
houses_original

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])