# Indexing

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
A[0,2]

3

# Slicing A[début : fin, début : fin]

In [6]:
A[:,0] # Permet de récupérer la colonne

array([1, 4, 7])

In [8]:
A[0,:] # Permet de récupérer la ligne

array([1, 2, 3])

In [10]:
B = A[0:2,0:2]
B

array([[1, 2],
       [4, 5]])

In [19]:
C =A[:,-2:]
C

array([[2, 3],
       [5, 6],
       [8, 9]])

In [20]:
B = np.zeros((4,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
B[1:3,1:3] = 1
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [ ]:
C = np.zeros((5,5))
C